# Changes here will be overwritten by Copier
_commit: 0.14.2
_src_path: gh:bhklab/bhklab-project-template
author_email: julianguyen.bhklab@gmail.com
author_full_name: Julia Nguyen
github_username: julianguyn
has_additional_authors: false
project_description: A pipeline for scoring samples based on given peak sets.
project_name: Peak Set Scoring Pipeline
project_slug: peak-set-scoring
publish_to_github: true
python_version: '3.12'
repo_location: julianguyn
